### ISSUE TITLE
Cannot run application

### ISSUE THREAD

**Issue by samuelksmith** [fhsinchy/movieist#3]
<img width="2508" alt="CleanShot 2023-05-25 at 13 26 59@2x" src="https://github.com/fhsinchy/movieist/assets/127219445/0d58c173-d4b9-4167-816c-c83308207407">

I'm getting this error when trying to run my application. I believe I have MongoDB setup correctly as well..

<img width="1276" alt="CleanShot 2023-05-25 at 13 27 40@2x" src="https://github.com/fhsinchy/movieist/assets/127219445/b2c03000-e8d3-4edc-a903-2cf5f4b09380">

I'm copying the connection string straight out of the MongoDB Compass application.

**Comment by robinwittkamp** [comment]
Maybe you misspelled the name of the database?
The line to set the database in the `application.properties` file should look like this:
```
spring.data.mongodb.database=movie-api-db
```

**Comment by robinwittkamp** [comment]
You can fix it by adding `${spring.data.mongodb.database}` at the end of your URI.

**Example:**
```
spring.data.mongodb.database=movie-api-db
spring.data.mongodb.uri=mongodb+srv://username:password@cluster/${spring.data.mongodb.database}
```

Replace `username`, `password` and `cluster` in the URI with your credentials.

**Source:**
[https://github.com/spring-projects/spring-boot/issues/35566](https://github.com/spring-projects/spring-boot/issues/35566)

**Comment by samuelksmith** [comment]
> You can fix it by adding `${spring.data.mongodb.database}` at the end of your URI.
> 
> **Example:**
> 
> ```
> spring.data.mongodb.database=movie-api-db
> spring.data.mongodb.uri=mongodb+srv://username:password@cluster/${spring.data.mongodb.database}
> ```
> 
> Replace `username`, `password` and `cluster` in the URI with your credentials.
> 
> **Source:** [spring-projects/spring-boot#35566](https://github.com/spring-projects/spring-boot/issues/35566)

Thank you!
